# Generated by Django 5.1 on 2024-09-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
