# Generated by Django 5.1 on 2024-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_remove_user_otp_remove_user_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/images/default.jpg', upload_to='images'),
        ),
    ]
