# Generated by Django 5.1 on 2024-09-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_intra',
        ),
    ]
