# Generated by Django 5.1 on 2024-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0012_user_logged_in_user_otp_base32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_base32',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
