# Generated by Django 5.1 on 2024-10-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0015_profile_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='user',
            new_name='component',
        ),
    ]
