# Generated by Django 5.1 on 2024-10-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0017_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='component',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='tmp_text',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='played_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='user1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='user1_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='user2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='user2_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stats',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='losses',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='wins',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
