# Generated by Django 5.1 on 2024-10-12 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0020_user_score_alter_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
