# Generated by Django 5.1 on 2024-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0021_remove_stats_id_alter_relationship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
