# Generated by Django 5.1 on 2024-10-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0022_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('send', 'send')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stats',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
