# Generated by Django 5.1 on 2024-12-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0027_alter_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
