# Generated by Django 5.1 on 2024-12-21 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0028_remove_relationship_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_of_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
