# Generated by Django 5.1 on 2025-01-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0029_friendsprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendsprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendsProfile',
        ),
    ]
