# Generated by Django 5.1 on 2025-01-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0031_matchhistory_game_type_matchhistory_is_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='game_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
