# Generated by Django 5.1 on 2025-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0032_matchhistory_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_otp',
            field=models.BooleanField(default=True),
        ),
    ]
