# Generated by Django 5.1 on 2025-01-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0033_user_use_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
