# Generated by Django 5.1 on 2025-01-20 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0034_matchhistory_date_matchhistory_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='time',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
