
services:

  postgree_db:
    image: postgres:15
    container_name: postgree_db
    env_file:
      - .env
    restart: always

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    depends_on:
      - postgree_db
    container_name: backend
    image: backend
    build: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  

  ponggame:
    container_name: ponggame
    image: ponggame
    build: ./PongGame
    volumes:
      - ./PongGame:/app

  frontend:
    depends_on:
      - backend
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./backend/media/images:/usr/share/nginx/html/media/images


  blockchain:
    build: ./blockchain
    ports:
      - "8545:8545" 
    volumes:
      - ./blockchain:/usr/src/app 

  tictactoe:
    container_name: tictactoe
    image: tictactoe
    build: ./TicTacToe

    volumes:
      - ./TicTacToe:/app
  
  
volumes:
  postgres_data: